#include "web_binding_state.hpp"
#include "gaze_tracker.hpp"
#include <godot_cpp/classes/java_script_bridge.hpp>

#ifdef WEB_ENABLED
namespace godot {

void WebBindingState::setup_callbacks(GazeTracker* tracker) {
    JavaScriptBridge *js = JavaScriptBridge::get_singleton();
    if (!js) return;

    permission_callback = js->create_callback(Callable(tracker, "on_permission_result"));
    feed_callback = js->create_callback(Callable(tracker, "feed_gaze_web_raw"));

    Ref<JavaScriptObject> window = js->get_interface("window");
    window->set("gaze_permission_callback", permission_callback);
    window->set("gaze_feed_callback", feed_callback);
}

void WebBindingState::start_tracking_loop(GazeTracker* tracker, const String& yunet_path, const String& gaze_onnx_path) {
    JavaScriptBridge *js = JavaScriptBridge::get_singleton();
    if (!js) return;

    Ref<JavaScriptObject> window = js->get_interface("window");
    window->set("gaze_yunet_path", yunet_path);
    window->set("gaze_onnx_path", gaze_onnx_path);

    js->eval(
        "if (!window.gaze_tracking_active) {"
        "    window.gaze_tracking_active = true;"
        "    console.log('[GazeTracker] Loading opencv.js...');"
        "    var s = document.createElement('script');"
        "    s.crossOrigin = 'anonymous';"
        "    s.src = 'opencv.js';"
        "    s.onload = function() {"
        "        console.log('[GazeTracker] Local opencv.js loaded. Waiting for Runtime...');"
        "        var checkInitialized = setInterval(function() {"
        "            if (typeof cv !== 'undefined' && cv.RuntimeError === undefined) {"
        "                clearInterval(checkInitialized);"
        "                console.log('[GazeTracker] OpenCV.js Runtime initialized. Starting pipeline...');"
        "                initializePipeline();"
        "            }"
        "        }, 100);"
        "    };"
        "    s.onerror = function(err) {"
        "        console.warn('[GazeTracker] Local opencv.js failed to load. Trying CDN fallback...');"
        "        var sCDN = document.createElement('script');"
        "        sCDN.crossOrigin = 'anonymous';"
        "        sCDN.src = 'https://cdn.jsdelivr.net/npm/@techstark/opencv-js@4.9.0-release.2/dist/opencv.js';"
        "        sCDN.onload = s.onload;"
        "        sCDN.onerror = function(cdnErr) {"
        "            console.error('[GazeTracker] Failed to load opencv.js from CDN:', cdnErr);"
        "        };"
        "        document.head.appendChild(sCDN);"
        "    };"
        "    document.head.appendChild(s);"
        ""
        "    function initializePipeline() {"
        "        var fs = (typeof FS !== 'undefined') ? FS : (Module && Module.FS);"
        "        if (!fs) {"
        "            console.error('[GazeTracker] Emscripten FS module not found.');"
        "            return;"
        "        }"
        ""
        "        console.log('[GazeTracker] Traversing VFS to find models...');"
        "        function traverse(dir) {"
        "            try {"
        "                var entries = fs.readdir(dir);"
        "                for (var i = 0; i < entries.length; i++) {"
        "                    var entry = entries[i];"
        "                    if (entry !== '.' && entry !== '..') {"
        "                        var full = dir === '/' ? '/' + entry : dir + '/' + entry;"
        "                        var stat = fs.stat(full);"
        "                        if (fs.isDir(stat.mode)) {"
        "                            traverse(full);"
        "                        } else if (entry.indexOf('face_detection_') !== -1 || entry.indexOf('gaze-') !== -1) {"
        "                            console.log('[GazeTracker] Found model in VFS at:', full, 'size:', stat.size);"
        "                        }"
        "                    }"
        "                }"
        "            } catch (e) {}"
        "        }"
        "        traverse('/');"
        ""
        "        var yunetPath = window.gaze_yunet_path || '/userfs/models/face_detection_yunet_2023mar.onnx';"
        "        var gazeOnnxPath = window.gaze_onnx_path || '/userfs/models/gaze-estimation-adas-0002.onnx';"
        ""
        "        if (!fs.analyzePath(yunetPath).exists) {"
        "            console.error('[GazeTracker] YuNet model file missing in VFS:', yunetPath);"
        "            return;"
        "        }"
        "        if (!fs.analyzePath(gazeOnnxPath).exists) {"
        "            console.error('[GazeTracker] Gaze ONNX model file missing in VFS:', gazeOnnxPath);"
        "            return;"
        "        }"
        ""
        "        console.log('[GazeTracker] Copying models to cv.FS (isolated OpenCV filesystem)...');"
        "        if (typeof cv.FS === 'undefined') {"
        "            console.error('[GazeTracker] cv.FS is not defined! Cannot write to OpenCV VFS.');"
        "            return;"
        "        }"
        "        function copyToCvFS(srcPath, destPath) {"
        "            try {"
        "                var data = fs.readFile(srcPath);"
        "                var parts = destPath.split('/');"
        "                var currentDir = '';"
        "                for (var i = 0; i < parts.length - 1; i++) {"
        "                    if (parts[i] === '') continue;"
        "                    currentDir += '/' + parts[i];"
        "                    try { cv.FS.mkdir(currentDir); } catch(e) {}"
        "                }"
        "                cv.FS.writeFile(destPath, data);"
        "                console.log('[GazeTracker] Copied to cv.FS:', destPath, 'size:', data.length);"
        "            } catch (e) {"
        "                console.error('[GazeTracker] Failed to copy to cv.FS:', srcPath, 'to', destPath, e);"
        "            }"
        "        }"
        "        var cvYunetPath = '/models/face_detection_yunet_2023mar.onnx';"
        "        var cvGazeOnnxPath = '/models/gaze-estimation-adas-0002.onnx';"
        "        copyToCvFS(yunetPath, cvYunetPath);"
        "        copyToCvFS(gazeOnnxPath, cvGazeOnnxPath);"
        ""
        "        try {"
        "            var detector = cv.FaceDetectorYN ? cv.FaceDetectorYN.create(cvYunetPath, '', new cv.Size(320, 240), 0.6, 0.3, 5000) : cv.readNet(cvYunetPath);"
        "            var gazeNet = cv.readNet(cvGazeOnnxPath);"
        "            console.log('[GazeTracker] OpenCV networks loaded successfully.');"
        "        } catch (err) {"
        "            var msg = err;"
        "            if (typeof err === 'number' && typeof cv !== 'undefined' && cv.exceptionFromPtr) {"
        "                try { msg = cv.exceptionFromPtr(err).msg; } catch(e) {}"
        "            } else if (err && err.message) {"
        "                msg = err.message;"
        "            }"
        "            console.error('[GazeTracker] Failed to read networks via OpenCV.js:', msg);"
        "            return;"
        "        }"
        ""
        "        var video = document.createElement('video');"
        "        video.width = 320;"
        "        video.height = 240;"
        "        video.autoplay = true;"
        "        video.playsInline = true;"
        "        video.muted = true;"
        "        video.style.display = 'none';"
        "        document.body.appendChild(video);"
        ""
        "        navigator.mediaDevices.getUserMedia({"
        "            video: { width: 320, height: 240, facingMode: 'user' }"
        "        }).then(function(stream) {"
        "            video.srcObject = stream;"
        "            video.play();"
        ""
        "            var cap = new cv.VideoCapture(video);"
        "            var frame = new cv.Mat(video.height, video.width, cv.CV_8UC4);"
        "            var bgr = new cv.Mat();"
        "            var gray = new cv.Mat();"
        "            var faces = new cv.Mat();"
        ""
        "            function trackFrame() {"
        "                if (!window.gaze_tracking_active) {"
        "                    stream.getTracks().forEach(function(track) { track.stop(); });"
        "                    video.remove();"
        "                    frame.delete();"
        "                    bgr.delete();"
        "                    gray.delete();"
        "                    faces.delete();"
        "                    if (detector && detector.delete) detector.delete();"
        "                    gazeNet.delete();"
        "                    console.log('[GazeTracker] Web tracking loop stopped.');"
        "                    return;"
        "                }"
        "                if (video.paused || video.ended) {"
        "                    requestAnimationFrame(trackFrame);"
        "                    return;"
        "                }"
        "                try {"
        "                    cap.read(frame);"
        "                    cv.cvtColor(frame, bgr, cv.COLOR_RGBA2BGR);"
        "                    cv.cvtColor(bgr, gray, cv.COLOR_BGR2GRAY);"
        ""
        "                    var detected = false;"
        "                    var landmarks = [];"
        ""
        "                    if (cv.FaceDetectorYN && detector.detect) {"
        "                        detector.setInputSize(bgr.size());"
        "                        detector.detect(bgr, faces);"
        "                        if (faces.rows > 0) {"
        "                            detected = true;"
        "                            for (var i = 0; i < 5; i++) {"
        "                                landmarks.push({ x: faces.data32F[4 + 2 * i], y: faces.data32F[5 + 2 * i] });"
        "                            }"
        "                        }"
        "                    } else {"
        "                        var blob = cv.blobFromImage(bgr, 1.0, new cv.Size(320, 240), new cv.Scalar(0, 0, 0, 0), false, false);"
        "                        detector.setInput(blob);"
        "                        var outs = detector.forward();"
        "                        if (!outs.empty() && outs.rows > 0) {"
        "                            detected = true;"
        "                            for (var i = 0; i < 5; i++) {"
        "                                landmarks.push({ x: outs.data32F[4 + 2 * i], y: outs.data32F[5 + 2 * i] });"
        "                            }"
        "                        }"
        "                        blob.delete();"
        "                        outs.delete();"
        "                    }"
        ""
        "                    if (detected && landmarks.length >= 5) {"
        "                        var model_points = cv.matFromArray(5, 3, cv.CV_32F, ["
        "                            -30.0, -28.676, 0.0,"
        "                            30.0, -28.676, 0.0,"
        "                            0.0, -3.5, -13.0,"
        "                            -18.462, 31.712, -4.55,"
        "                            18.462, 31.712, -4.55"
        "                        ]);"
        "                        var image_points = cv.matFromArray(5, 2, cv.CV_32F, ["
        "                            landmarks[0].x, landmarks[0].y,"
        "                            landmarks[1].x, landmarks[1].y,"
        "                            landmarks[2].x, landmarks[2].y,"
        "                            landmarks[3].x, landmarks[3].y,"
        "                            landmarks[4].x, landmarks[4].y"
        "                        ]);"
        "                        var cx = video.width / 2.0;"
        "                        var cy = video.height / 2.0;"
        "                        var fx = video.width * 1.5625;"
        "                        var camera_matrix = cv.matFromArray(3, 3, cv.CV_64F, ["
        "                            fx, 0.0, cx,"
        "                            0.0, fx, cy,"
        "                            0.0, 0.0, 1.0"
        "                        ]);"
        "                        var dist_coeffs = cv.Mat.zeros(4, 1, cv.CV_64F);"
        "                        var rvec = cv.matFromArray(3, 1, cv.CV_64F, [0.0, 0.0, 0.0]);"
        "                        var tvec = cv.matFromArray(3, 1, cv.CV_64F, [0.0, 0.0, 700.0]);"
        "                        var pnp_success = cv.solvePnP(model_points, image_points, camera_matrix, dist_coeffs, rvec, tvec, true, cv.SOLVEPNP_ITERATIVE);"
        ""
        "                        if (pnp_success) {"
        "                            var R = new cv.Mat();"
        "                            cv.Rodrigues(rvec, R);"
        "                            var r00 = R.doubleAt(0, 0); var r10 = R.doubleAt(1, 0); var r20 = R.doubleAt(2, 0);"
        "                            var r01 = R.doubleAt(0, 1); var r11 = R.doubleAt(1, 1); var r21 = R.doubleAt(2, 1);"
        "                            var r02 = R.doubleAt(0, 2); var r12 = R.doubleAt(1, 2); var r22 = R.doubleAt(2, 2);"
        "                            var sy = Math.sqrt(r00 * r00 + r10 * r10);"
        "                            var singular = sy < 1e-6;"
        "                            var pitch = 0, yaw = 0, roll = 0;"
        "                            if (!singular) {"
        "                                pitch = Math.atan2(r21, r22) * (180.0 / Math.PI);"
        "                                yaw   = Math.atan2(-r20, sy) * (180.0 / Math.PI);"
        "                                roll  = Math.atan2(r10, r00) * (180.0 / Math.PI);"
        "                            } else {"
        "                                pitch = Math.atan2(-r12, r11) * (180.0 / Math.PI);"
        "                                yaw   = Math.atan2(-r20, sy) * (180.0 / Math.PI);"
        "                                roll  = 0;"
        "                            }"
        "                            pitch += 0.017 * tvec.doubleAt(1, 0);"
        "                            yaw += 0.017 * tvec.doubleAt(0, 0);"
        ""
        "                            function cropEye(isLeft) {"
        "                                var eye_center = isLeft ? landmarks[1] : landmarks[0];"
        "                                var pt = new cv.Point(eye_center.x, eye_center.y);"
        "                                var roll_dx = landmarks[1].x - landmarks[0].x;"
        "                                var roll_dy = landmarks[1].y - landmarks[0].y;"
        "                                var angle = Math.atan2(roll_dy, roll_dx) * (180.0 / Math.PI);"
        "                                var scale = 1.0;"
        "                                var target_size = new cv.Size(60, 60);"
        "                                var M = cv.getRotationMatrix2D(pt, angle, scale);"
        "                                pt.delete();"
        "                                M.data64F[2] += (target_size.width / 2.0) - eye_center.x;"
        "                                M.data64F[5] += (target_size.height / 2.0) - eye_center.y;"
        "                                var warped = new cv.Mat();"
        "                                cv.warpAffine(gray, warped, M, target_size, cv.INTER_LINEAR, cv.BORDER_REPLICATE);"
        "                                var warped_bgr = new cv.Mat();"
        "                                cv.cvtColor(warped, warped_bgr, cv.COLOR_GRAY2BGR);"
        "                                M.delete();"
        "                                warped.delete();"
        "                                return warped_bgr;"
        "                            }"
        ""
        "                            var left_eye_mat = cropEye(true);"
        "                            var right_eye_mat = cropEye(false);"
        "                            var left_blob = cv.blobFromImage(left_eye_mat, 1.0, new cv.Size(60, 60), new cv.Scalar(0, 0, 0, 0), false, false);"
        "                            var right_blob = cv.blobFromImage(right_eye_mat, 1.0, new cv.Size(60, 60), new cv.Scalar(0, 0, 0, 0), false, false);"
        "                            var head_pose_data = cv.matFromArray(1, 3, cv.CV_32F, [-yaw, pitch, -roll]);"
        ""
        "                            gazeNet.setInput(right_blob, 'left_eye_image');"
        "                            gazeNet.setInput(left_blob, 'right_eye_image');"
        "                            gazeNet.setInput(head_pose_data, 'head_pose_angles');"
        ""
        "                            var output = gazeNet.forward('gaze_vector');"
        "                            if (!output.empty()) {"
        "                                var dx = 0, dy = 0, dz = 0;"
        "                                if (output.cols === 2) {"
        "                                    var pitch_gaze = output.floatAt(0, 0);"
        "                                    var yaw_gaze = output.floatAt(0, 1);"
        "                                    var cos_pitch = Math.cos(pitch_gaze);"
        "                                    dx = Math.sin(yaw_gaze) * cos_pitch;"
        "                                    dy = Math.sin(pitch_gaze);"
        "                                    dz = Math.cos(yaw_gaze) * cos_pitch;"
        "                                } else if (output.cols === 3) {"
        "                                    dx = output.floatAt(0, 0);"
        "                                    dy = output.floatAt(0, 1);"
        "                                    dz = output.floatAt(0, 2);"
        "                                }"
        "                                var len_gaze = Math.hypot(dx, dy, dz);"
        "                                if (len_gaze > 0) {"
        "                                    dx /= len_gaze; dy /= len_gaze; dz /= len_gaze;"
        "                                }"
        "                                var tx = tvec.doubleAt(0, 0);"
        "                                var ty = tvec.doubleAt(1, 0);"
        "                                var tz = tvec.doubleAt(2, 0);"
        "                                var lex = r00 * 30.0 + r01 * -20.0 + tx;"
        "                                var ley = r10 * 30.0 + r11 * -20.0 + ty;"
        "                                var lez = r20 * 30.0 + r21 * -20.0 + tz;"
        "                                var rex = r00 * -30.0 + r01 * -20.0 + tx;"
        "                                var rey = r10 * -30.0 + r11 * -20.0 + ty;"
        "                                var rez = r20 * -30.0 + r21 * -20.0 + tz;"
        "                                var ox = (lex + rex) / 2.0;"
        "                                var oy = (ley + rey) / 2.0;"
        "                                var oz = (lez + rez) / 2.0;"
        ""
        "                                if (window.gaze_feed_callback) {"
        "                                    window.gaze_feed_callback(ox, oy, oz, dx, dy, dz);"
        "                                }"
        "                            }"
        ""
        "                            R.delete();"
        "                            left_eye_mat.delete();"
        "                            right_eye_mat.delete();"
        "                            left_blob.delete();"
        "                            right_blob.delete();"
        "                            head_pose_data.delete();"
        "                            output.delete();"
        "                        }"
        "                        model_points.delete();"
        "                        image_points.delete();"
        "                        camera_matrix.delete();"
        "                        dist_coeffs.delete();"
        "                        rvec.delete();"
        "                        tvec.delete();"
        "                    }"
        "                } catch (err) {"
        "                    console.error('[GazeTracker] Frame loop error:', err);"
        "                }"
        "                requestAnimationFrame(trackFrame);"
        "            }"
        "            trackFrame();"
        "        }).catch(function(err) {"
        "            console.error('[GazeTracker] Camera failed to start:', err);"
        "        });"
        "    }"
        "}"
    );
}

void WebBindingState::cleanup() {
    JavaScriptBridge *js = JavaScriptBridge::get_singleton();
    if (js) {
        js->eval(
            "window.gaze_tracking_active = false;"
            "if (window.gaze_permission_callback) { delete window.gaze_permission_callback; }"
            "if (window.gaze_feed_callback) { delete window.gaze_feed_callback; }"
            "if (window.gaze_yunet_path) { delete window.gaze_yunet_path; }"
            "if (window.gaze_xml_path) { delete window.gaze_xml_path; }"
            "if (window.gaze_bin_path) { delete window.gaze_bin_path; }"
        );
    }
    permission_callback.unref();
    feed_callback.unref();
}

} // namespace godot
#endif
